[package]
name = "check-buddy-pgn-parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
check-buddy-core = { path = "../check-buddy-core" }
anyhow = "1.0"
