[package]
name = "check-buddy"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["crates/*"]

[dependencies]
check-buddy-core = {path="crates/check-buddy-core"}

[profile.dev.package."*"]
opt-level = 3

[profile.dev]
opt-level = 1

[profile.release]
lto = "thin"
opt-level = 'z'
