[package]
name = "chess"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["bevy","bevy-inspector-egui"]
debug = ["colored"]

[dependencies]
bevy = {version="0.7",optional=true}
clap = "3.1.6"
colored = { version = "2.0", optional = true }
bevy-inspector-egui = {version= "0.10.0",optional=true}
clearscreen = "1.0.9"