[package]
name = "check-buddy-core"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8"
anyhow = "1"
thiserror = "1"

[dev-dependencies]
criterion = "0.4"
calamine = "0.19"
csv = "1.1"

[[bench]]
name = "generate_moves"
harness = false
