[package]
name = "check-buddy-shell"
version = "0.1.0"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
check-buddy = { path = "../../check-buddy" }
